/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 15 janv. 2013, 21:55:44
 */

package com.masim.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.masim.utils.SimulationFramework;

/**
 * 
 * @author Sabri Ghazi
 */
public class SimulationConfigDilog extends javax.swing.JDialog {

    /** Creates new form NewJFrame */
    public SimulationConfigDilog(java.awt.Frame parent, boolean modal) {
    	super(parent, modal);
    	setTitle("Simulation parameters and data path");
        initComponents();
        OK_btn.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent e) {
				SimulationFramework.getCurrentEnv().DATA_PATH=dataPath_txt.getText();
				
				int maxTime=Integer.parseInt(numberOfTimeStep_txt.getText());
				int startTime=Integer.parseInt(startTimeSte_txt.getText());
				int numberOfStepAhead=Integer.parseInt(predictionStep_txt.getValue().toString()); 
				//int x=Integer.parseInt()
				//int y=
				
				SimulationFramework.getCurrentEnv().setMax_T(maxTime);
				SimulationFramework.getCurrentEnv().numberOfStepAhead=numberOfStepAhead;
				SimulationFramework.getCurrentEnv().T=startTime;
				SimulationFramework.getCurrentEnv().intitEnv(40,40, maxTime,numberOfStepAhead);
				SimulationFramework.loadEnvironmentData();
				setVisible(false);
			}});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPath_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numberOfTimeStep_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numerOfBoxtxt = new javax.swing.JTextField();
        OK_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        predictionStep_txt = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        startTimeSte_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        

        jLabel1.setText("DATA_PATH");

        jLabel2.setText("Number of time step");

        jLabel3.setText("Number of BOX");

        OK_btn.setText("Ok");

        Cancel_btn.setText("Cancel");

        jLabel4.setText("Step in advance");

        jLabel5.setText("Start  Time Step number :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(OK_btn)
                .addGap(18, 18, 18)
                .addComponent(Cancel_btn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(predictionStep_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(numerOfBoxtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(dataPath_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(numberOfTimeStep_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startTimeSte_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataPath_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberOfTimeStep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numerOfBoxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(predictionStep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeSte_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel_btn)
                    .addComponent(OK_btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_btn;
    public javax.swing.JButton OK_btn;
    public javax.swing.JTextField dataPath_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField numberOfTimeStep_txt;
    public javax.swing.JTextField numerOfBoxtxt;
    public javax.swing.JSpinner predictionStep_txt;
    public javax.swing.JTextField startTimeSte_txt;
    // End of variables declaration//GEN-END:variables

}
